if (!requireNamespace("BiocManager",
 quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.10")
mypackages <- c("XML",
	"xml2",
	"devtools",
	"microbenchmark",
	"roxygen2",
	"mclust",
	"fastcluster",
	"ppcor",
	"RMySQL",
	"igraph",
	"rJava",
	"pheatmap",
	"BiocStyle",
	"compEpiTools",
	"DESeq2",
	"DEXSeq",
	"GEOmetadb",
	"clusterProfiler",
	"msigdbr",
	"BSgenome.Hsapiens.UCSC.hg18",
	"BSgenome.Hsapiens.UCSC.hg19",
	"BSgenome.Mmusculus.UCSC.mm9",
	"BSgenome.Mmusculus.UCSC.mm10",
	"TxDb.Hsapiens.UCSC.hg18.knownGene",
	"TxDb.Hsapiens.UCSC.hg38.knownGene",
	"TxDb.Mmusculus.UCSC.mm9.knownGene",
	"org.Mm.eg.db",
	"recount",
	"SRAdb",
	"INSPEcT",
	"Onassis")
BiocManager::install(mypackages)
